# Generated by Django 2.0.4 on 2018-09-07 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecolumn',
            options={'verbose_name': '文章字段', 'verbose_name_plural': '文章字段'},
        ),
    ]
